'use strict';
(() => {
const $=s=>document.querySelector(s), canvas=$('#world'),ctx=canvas.getContext('2d'),modal=$('#modal'),body=$('#modalBody');
const KEY='isadora-discoveries-v2';
const defaults={completed:[],best:{},resume:null,settings:{music:true,voice:true,effects:true,pace:'calm',motion:true}};
let save;try{save=JSON.parse(localStorage.getItem(KEY))||{}}catch{save={}}save={...defaults,...save,settings:{...defaults.settings,...save.settings}};save.completed=Array.isArray(save.completed)?save.completed.filter(n=>Number.isInteger(n)&&n>=0&&n<7):[];save.best=save.best&&typeof save.best==='object'?save.best:{};
const persist=()=>{try{localStorage.setItem(KEY,JSON.stringify(save))}catch{toast('O navegador não permitiu salvar o progresso.')}};
const words=['Abelha','Bola','Casa','Dado','Elefante','Fada','Gato','Hipopótamo','Igreja','Jacaré','Kiwi','Leão','Macaco','Navio','Ovo','Pato','Queijo','Rato','Sapo','Tatu','Uva','Vaca','Waffle','Xícara','Yakisoba','Zebra'];
const initial=[['BOLA','B',['D','P']],['CASA','C',['G','O']],['FADA','F',['V','T']],['GATO','G',['C','J']],['PATO','P',['B','R']],['UVA','U',['A','E']],['SAPO','S',['Z','M']],['LEÃO','L',['I','R']]];
const syllables=[['BOLA','BO',['BA','BE']],['MACACO','MA',['ME','MI']],['CASA','CA',['CO','CU']],['DADO','DA',['DE','DI']],['PATO','PA',['PE','PO']],['VACA','VA',['VE','VI']],['FADA','FA',['FE','FO']],['SAPO','SA',['SE','SI']],['LATA','LA',['LE','LI']],['GATO','GA',['GO','GU']]];
const memory=[['MACACO','M',['N','W']],['FADA','F',['V','T']],['SAPO','S',['Z','C']],['BOLA','B',['P','D']],['PATO','P',['B','Q']],['VACA','V',['F','U']],['LEÃO','L',['I','R']],['DADO','D',['B','T']],['GATO','G',['C','J']],['RATO','R',['H','L']]];
const sentences=[['O _____ MIA.','GATO',['PATO','RATO']],['A _____ BOTA OVO.','AVE',['UVA','PIA']],['O MACACO COME _____.','BANANA',['MOLA','MALA']],['O _____ LATE.','CÃO',['PÃO','MÃO']],['EU MORO EM UMA _____.','CASA',['CAMA','MESA']]];
const flight='ISADORAAMORVITÓRIA'.split('');
const levels=[
{name:'Jardim das letras',skill:'Alfabeto de A a Z',area:0,accent:'#edcc79',ground:'#627b45',type:'collect',total:26,intro:'Encontre as letras em ordem, de A até Z. Pule os obstáculos pelo caminho.'},
{name:'Vale dos enigmas',skill:'Letras iniciais',area:0,accent:'#edaa8c',ground:'#8c7150',type:'quiz',total:8,intro:'Atravesse o vale. Em cada portal, descubra a primeira letra de uma palavra.'},
{name:'Ilhas dos sonhos',skill:'Voo e palavras',area:1,accent:'#d5b6ed',ground:'#8b82ad',type:'fly',total:flight.length,intro:'Segure o botão para subir e solte para descer. Reúna as letras de ISADORA, AMOR e VITÓRIA.'},
{name:'Castelo das sílabas',skill:'Sílabas iniciais',area:1,accent:'#bdb8f4',ground:'#807495',type:'quiz',total:10,intro:'Passe pelos jardins do castelo e descubra com qual sílaba cada palavra começa.'},
{name:'Bosque da memória',skill:'Escutar e reconhecer',area:2,accent:'#8fd8c9',ground:'#315b57',type:'quiz',total:10,intro:'Escute a palavra e escolha a letra inicial. Você também pode ler a palavra na tela.'},
{name:'Ponte das palavras',skill:'Completar frases',area:2,accent:'#e6c48b',ground:'#796548',type:'quiz',total:5,intro:'Atravesse as pontes iluminadas e escolha palavras para completar as frases.'},
{name:'Festival dos números',skill:'Contagem de 1 a 10',area:0,accent:'#efb8c4',ground:'#797c4f',type:'quiz',total:10,intro:'Chegou o festival! Conte as estrelas e encontre o número correspondente.'}
];
const art=new Image(),sprite=new Image();art.src='assets/mundos.png';sprite.src='assets/isadora.png';
// Source rectangles align the original, irregularly spaced poses at their feet.
const frames=[[32,426,250,370],[746,191,278,390],[1210,350,320,385]];
let W=innerWidth,H=innerHeight,D=1,ground=H*.78,scale=1,time=0,last=0,mode='loading',level=0,step=0,score=0,lives=3,combo=0,mistakes=0,elapsed=0,distance=0,spawnTime=0,quizClock=0,invincible=0,held=false,objects=[],particles=[],pending=0,bookPage=0,returnFocus=null;
const player={x:160,y:0,vy:0,jumps:0};let musicGame=new Audio('assets/musica_jogo.mp3'),musicMenu=new Audio('assets/musica_menu.mp3');musicGame.loop=musicMenu.loop=true;musicGame.volume=.2;musicMenu.volume=.16;let audioContext;
const reduced=()=>!save.settings.motion||matchMedia('(prefers-reduced-motion: reduce)').matches;
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),2200)}
function audio(which){musicGame.pause();musicMenu.pause();if(save.settings.music)(which==='game'?musicGame:musicMenu).play().catch(()=>{});}
function tone(good=true){if(!save.settings.effects)return;try{audioContext??=new(window.AudioContext||window.webkitAudioContext)();audioContext.resume();let o=audioContext.createOscillator(),g=audioContext.createGain(),t=audioContext.currentTime;o.type='sine';o.frequency.setValueAtTime(good?650:230,t);o.frequency.exponentialRampToValueAtTime(good?980:170,t+.16);g.gain.setValueAtTime(.065,t);g.gain.exponentialRampToValueAtTime(.001,t+.24);o.connect(g);g.connect(audioContext.destination);o.start();o.stop(t+.25)}catch{}}
function speak(text){if(!save.settings.voice||!('speechSynthesis'in window))return;speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(text);u.lang='pt-BR';u.rate=.85;let v=speechSynthesis.getVoices().find(v=>v.lang==='pt-BR');if(v)u.voice=v;speechSynthesis.speak(u)}
function quiet(){musicGame.pause();if('speechSynthesis'in window)speechSynthesis.cancel();held=false}
function resize(){let oldGround=ground,offset=oldGround-player.y;W=innerWidth;H=innerHeight;D=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(W*D);canvas.height=Math.round(H*D);scale=Math.max(.62,Math.min(1.25,H/650));ground=H-(H<500?77:125);player.x=Math.min(W*.21,190*scale);player.y=ground-offset;player.y=Math.max(140*scale,Math.min(ground,player.y));for(const o of objects)if(o.kind==='hazard')o.y=ground;}
addEventListener('resize',resize);resize();
function rect(x,y,w,h,r,fill,c=ctx){c.fillStyle=fill;c.beginPath();c.roundRect(x,y,w,h,r);c.fill()}
function ellipse(x,y,rx,ry,color,c=ctx){c.fillStyle=color;c.beginPath();c.ellipse(x,y,rx,ry,0,0,Math.PI*2);c.fill()}
function star(x,y,r,color,c=ctx){c.beginPath();for(let i=0;i<10;i++){let a=i*Math.PI/5-Math.PI/2,rr=i%2?r*.44:r;c.lineTo(x+Math.cos(a)*rr,y+Math.sin(a)*rr)}c.closePath();c.fillStyle=color;c.fill()}
function artRegion(area){const h=art.naturalHeight;return area===0?[0,0,art.naturalWidth,h*.310]:area===1?[0,h*.312,art.naturalWidth,h*.310]:[0,h*.625,art.naturalWidth,h*.375]}
function background(c,w,h,l,pan=0){const conf=levels[l];if(art.naturalWidth){let [sx,sy,sw,sh]=artRegion(conf.area);let ratio=Math.max(w/sw,h/sh),dw=sw*ratio*1.1,dh=sh*ratio*1.1;let x=(w-dw)/2+Math.sin(pan*.000045)*(dw-w)*.43;c.drawImage(art,sx,sy,sw,sh,x,(h-dh)/2,dw,dh)}else{c.fillStyle=['#98c9bd','#b1bfe7','#214255'][conf.area];c.fillRect(0,0,w,h)}if(l===1||l===3||l===6){c.fillStyle=['','','','rgba(116,87,170,.11)','','','rgba(255,199,124,.15)'][l]||'rgba(255,187,114,.13)';c.fillRect(0,0,w,h)}}
function drawSprite(c,x,y,height,pose=0){if(!sprite.naturalWidth)return;const f=frames[pose],width=f[2]/f[3]*height;c.drawImage(sprite,...f,x-width/2,y-height,width,height)}
function portrait(){let c=$('#portrait').getContext('2d');c.clearRect(0,0,450,520);drawSprite(c,225,495,435,2)}
function drawWorld(){ctx.setTransform(D,0,0,D,0,0);ctx.clearRect(0,0,W,H);let playing=['run','quiz','pause','intro','result'].includes(mode);background(ctx,W,H,playing?level:0,distance);if(!playing)return;
const conf=levels[level],s=scale;let fog=ctx.createLinearGradient(0,ground-130*s,0,H);fog.addColorStop(0,'#ffffff00');fog.addColorStop(1,conf.area===2?'#0d353caa':'#fff0c335');ctx.fillStyle=fog;ctx.fillRect(0,ground-130*s,W,H-ground+130*s);
// Foreground layers move independently of the distant panorama.
if(conf.type!=='fly'){
 if(level===5){for(let i=-1;i<W/(115*s)+2;i++){let x=i*115*s-(distance*.7)%(115*s);rect(x,ground-77*s,8*s,78*s,3*s,'#bca078');ctx.strokeStyle='#dec69b';ctx.lineWidth=4*s;ctx.beginPath();ctx.moveTo(x,ground-64*s);ctx.quadraticCurveTo(x+58*s,ground-43*s,x+115*s,ground-64*s);ctx.stroke()}}
 let g=ctx.createLinearGradient(0,ground,0,H);g.addColorStop(0,conf.ground);g.addColorStop(1,conf.area===2?'#142f39':'#3c5140');rect(0,ground,W,H-ground,0,g);rect(0,ground,W,7*s,0,conf.area===2?'#78aaa0':'#c3d695');rect(0,ground+7*s,W,4*s,0,'#132f3626');
 for(let i=-1;i<W/(95*s)+2;i++){let x=i*95*s-distance%(95*s);rect(x,ground+21*s,70*s,4*s,2*s,'#f6e6b829');ellipse(x+20*s,ground+44*s,12*s,3*s,'#142f3520')}
 for(let i=0;i<10;i++){let x=((i*233-distance*.8)%(W+250)+W+250)%(W+250)-80;let y=ground+60*s+(i%3)*13*s;ctx.strokeStyle=conf.area===2?'#448a81':'#759451';ctx.lineWidth=2*s;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+3*s,y-18*s);ctx.stroke();ellipse(x+3*s,y-20*s,4*s,4*s,conf.accent)}
}else{for(let i=0;i<4;i++){let x=((i*420-distance*.6)%(W+420)+W+420)%(W+420)-180;ellipse(x,H-65*s,130*s,23*s,'#fff8ee66');ellipse(x+70*s,H-75*s,80*s,34*s,'#fff8ee55')}}
if(level===6){ctx.strokeStyle='#faf0bd';ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(0,160*s);ctx.quadraticCurveTo(W/2,260*s,W,160*s);ctx.stroke();for(let i=0;i<15;i++){let x=W*i/14,y=160*s+50*s*Math.sin(Math.PI*i/14);ctx.fillStyle=['#eeb4bc','#dfcd85','#a8d5c7'][i%3];ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+17*s,y+4*s);ctx.lineTo(x+6*s,y+26*s);ctx.fill()}}
if(!reduced())for(let i=0;i<16;i++){let x=((i*167-distance*.17)%(W+40)+W+40)%(W+40),y=ground*.2+(i*61)%(ground*.65)+Math.sin(time+i)*9;ellipse(x,y,conf.area===2?2:1.5,conf.area===2?2:1.5,conf.area===2?'#b7ffe6aa':'#fff9d799')}
if(conf.type==='quiz'&&quizClock>3){let gx=Math.max(player.x+130*s,W-(quizClock-3)*120*s),gy=ground-155*s;ctx.save();ctx.shadowColor=conf.accent;ctx.shadowBlur=reduced()?0:22;let portal=ctx.createLinearGradient(gx,gy,gx,ground);portal.addColorStop(0,conf.accent+'88');portal.addColorStop(1,conf.accent+'11');rect(gx-44*s,gy,88*s,155*s,[44*s,44*s,0,0],portal);ctx.shadowBlur=0;ctx.strokeStyle=conf.accent;ctx.lineWidth=7*s;ctx.beginPath();ctx.moveTo(gx-46*s,ground);ctx.lineTo(gx-46*s,gy+46*s);ctx.arc(gx,gy+46*s,46*s,Math.PI,0);ctx.lineTo(gx+46*s,ground);ctx.stroke();star(gx,gy-20*s,13*s,'#ffe6a2');ctx.restore();}
for(const o of objects){if(o.kind==='hazard')drawHazard(o);else drawCollectible(o)}
let ph=126*s;ellipse(player.x,ground+4*s,34*s-Math.min(18*s,(ground-player.y)*.07),7*s,'#102d3540');
ctx.save();if(invincible>0)ctx.globalAlpha=.65+.3*Math.sin(time*22);if(conf.type==='fly'){
const by=player.y-ph-72*s;ctx.strokeStyle='#e9d5c4';ctx.lineWidth=2*s;ctx.beginPath();ctx.moveTo(player.x-27*s,by+46*s);ctx.lineTo(player.x-16*s,player.y-59*s);ctx.moveTo(player.x+27*s,by+46*s);ctx.lineTo(player.x+16*s,player.y-59*s);ctx.stroke();let bg=ctx.createRadialGradient(player.x-20*s,by-18*s,1,player.x,by,68*s);bg.addColorStop(0,'#ffe7d0');bg.addColorStop(.55,'#efb0c5');bg.addColorStop(1,'#ad7eaa');ellipse(player.x,by,48*s,60*s,bg);ellipse(player.x,by,19*s,59*s,'#ffebd933');drawSprite(ctx,player.x,player.y,ph*.78,2);
}else{let pose=player.y<ground-3?1:Math.floor(time*7)%2?2:0;drawSprite(ctx,player.x,player.y+(player.y>=ground-2&&!reduced()?Math.sin(time*14)*2*s:0),ph,pose)}ctx.restore();
for(const p of particles){ctx.globalAlpha=Math.max(0,p.life);star(p.x,p.y,5*s,p.color)}ctx.globalAlpha=1;
}
function drawHazard(o){const s=scale,x=o.x,y=ground,w=o.w,h=o.h;ellipse(x,y+4*s,w*.65,6*s,'#15363240');if(o.variant===1){let g=ctx.createLinearGradient(x-w/2,y-h,x+w/2,y);g.addColorStop(0,'#caa076');g.addColorStop(1,'#705943');rect(x-w/2,y-h,w,h,9*s,g);ctx.strokeStyle='#e5c298';ctx.lineWidth=3*s;ctx.strokeRect(x-w*.34,y-h*.8,w*.68,h*.63);ctx.beginPath();ctx.moveTo(x-w*.3,y-h*.75);ctx.lineTo(x+w*.3,y-h*.2);ctx.stroke()}else if(o.variant===2){let g=ctx.createLinearGradient(x,y-h,x,y);g.addColorStop(0,'#cceff0');g.addColorStop(1,'#698cb8');ctx.fillStyle=g;ctx.beginPath();ctx.moveTo(x-w*.55,y);ctx.lineTo(x-w*.4,y-h*.5);ctx.lineTo(x,y-h);ctx.lineTo(x+w*.45,y-h*.55);ctx.lineTo(x+w*.55,y);ctx.fill();ctx.fillStyle='#ffffff65';ctx.beginPath();ctx.moveTo(x,y-h);ctx.lineTo(x+4*s,y-3*s);ctx.lineTo(x-w*.4,y-h*.5);ctx.fill()}else{let g=ctx.createLinearGradient(x,y-h,x,y);g.addColorStop(0,'#b6c3aa');g.addColorStop(1,'#687c73');ctx.fillStyle=g;ctx.beginPath();ctx.moveTo(x-w*.6,y);ctx.quadraticCurveTo(x-w*.6,y-h*.6,x-w*.25,y-h*.88);ctx.quadraticCurveTo(x+w*.3,y-h*1.2,x+w*.6,y);ctx.fill();ellipse(x-w*.1,y-h*.65,w*.24,h*.13,'#dce0c16b')}
if(o.x>player.x&&o.x-player.x<230*s){ctx.fillStyle='#fff1c2';ctx.font=`bold ${18*s}px Trebuchet MS`;ctx.textAlign='center';ctx.fillText('↑',x,y-h-14*s)}}
function drawCollectible(o){let s=scale;ctx.save();ctx.translate(o.x,o.y);if(!reduced())ctx.translate(0,Math.sin(time*3+o.x*.003)*4*s);let glow=ctx.createRadialGradient(0,0,4,0,0,46*s);glow.addColorStop(0,'#fff1b755');glow.addColorStop(1,'#fff1b700');ctx.fillStyle=glow;ctx.fillRect(-46*s,-46*s,92*s,92*s);let g=ctx.createLinearGradient(-20*s,-25*s,20*s,25*s);g.addColorStop(0,'#fff9df');g.addColorStop(1,'#efcb7c');rect(-25*s,-29*s,50*s,58*s,13*s,g);ctx.strokeStyle='#fff8d7';ctx.lineWidth=2*s;ctx.strokeRect(-17*s,-20*s,34*s,40*s);ctx.fillStyle='#285250';ctx.textAlign='center';ctx.textBaseline='middle';ctx.font=`900 ${30*s}px Trebuchet MS`;ctx.fillText(o.text,0,2*s);ctx.restore()}
function burst(x,y){if(reduced())return;for(let i=0;i<15;i++)particles.push({x,y,vx:(Math.random()-.5)*200,vy:-Math.random()*170,life:1,color:['#f8d486','#fff6d4','#b1e4cb'][i%3]})}
function show(html){returnFocus=document.activeElement;body.innerHTML=html;if(!modal.open)modal.showModal();}
function close(){modal.close();if(returnFocus?.isConnected)returnFocus.focus();}
function map(){let grid=$('#levelGrid');grid.innerHTML='';levels.forEach((l,i)=>{let b=document.createElement('button');b.className='level-card';b.dataset.level=i;b.setAttribute('aria-label',`${i+1}. ${l.name}. ${l.skill}. ${save.completed.includes(i)?'Concluído':'Explorar'}`);b.innerHTML=`<canvas width="400" height="200"></canvas><span class="badge">${save.completed.includes(i)?'✓ CONCLUÍDO':String(i+1).padStart(2,'0')}</span><div class="card-copy"><small>MUNDO ${String(i+1).padStart(2,'0')}</small><strong>${l.name}</strong><span>${l.skill}</span></div>`;grid.appendChild(b);background(b.querySelector('canvas').getContext('2d'),400,200,i);b.onclick=()=>intro(i,false)});$('#mapProgress').textContent=`${save.completed.length} / 7 mundos concluídos`;$('#play').innerHTML=(validResume()?'Continuar aventura':'Começar aventura')+' <span>➜</span>';}
function validResume(){return save.resume&&Number.isInteger(save.resume.level)&&save.resume.level>=0&&save.resume.level<7&&Number.isInteger(save.resume.step)&&save.resume.step>=0&&save.resume.step<levels[save.resume.level].total;}
function home(){clearTimeout(pending);quiet();close();mode='home';$('#home').hidden=false;$('#gameUI').hidden=true;document.body.classList.remove('playing');objects=[];particles=[];map();audio('menu');window.scrollTo(0,0)}
function intro(i,resume){level=i;mode='intro';held=false;show(`<div class="eyebrow">MUNDO ${i+1} DE 7 · ${levels[i].skill.toUpperCase()}</div><h2>${levels[i].name}</h2><p>${levels[i].intro}</p><p class="question-small">${levels[i].type==='fly'?'Segure Espaço, ↑ ou o botão de voo.': 'Isadora corre sozinha. Use Espaço, ↑ ou o botão para pular. Um segundo toque dá um pulo extra.'}</p><div class="modal-actions"><button class="secondary" data-action="home">Voltar</button><button class="primary" id="startLevel">${resume?'Continuar':'Vamos explorar'} ➜</button></div>`);$('#startLevel').onclick=()=>start(i,resume)}
function start(i,resume=false){clearTimeout(pending);close();level=i;step=resume&&validResume()&&save.resume.level===i?save.resume.step:0;score=resume?Number(save.resume?.score)||0:0;mistakes=resume?Number(save.resume?.mistakes)||0:0;lives=3;combo=0;elapsed=0;distance=0;objects=[];particles=[];invincible=2;spawnTime=1.3;quizClock=0;held=false;player.y=levels[i].type==='fly'?H*.62:ground;player.vy=0;player.jumps=0;mode='run';$('#home').hidden=true;$('#gameUI').hidden=false;document.body.classList.add('playing');$('#jump').innerHTML=levels[i].type==='fly'?'↑ <span>VOAR</span>':'↑ <span>PULAR</span>';$('#jump').setAttribute('aria-label',levels[i].type==='fly'?'Segurar para voar':'Pular');$('#controlHint').textContent=levels[i].type==='fly'?'Segure para subir · solte para descer':'Espaço ou ↑ · dois toques, pulo duplo';checkpoint();hud();audio('game');speak(objective());}
function checkpoint(){save.resume={level,step,score,mistakes};persist()}
function objective(){let l=levels[level];if(l.type==='collect')return `Encontre a letra ${String.fromCharCode(65+step)} de ${words[step]||''}`;if(l.type==='fly'){let p=step<7?'ISADORA':step<11?'AMOR':'VITÓRIA';return `${p} · encontre ${flight[step]||''}`}return level===6?'Conte as estrelas nos portais':'Siga até o próximo portal'}
function hud(){let l=levels[level];$('#phaseName').textContent=`${String(level+1).padStart(2,'0')} · ${l.name.toUpperCase()}`;$('#objective').textContent=objective();$('#progressFill').style.width=`${step/l.total*100}%`;$('#hearts').textContent='♥ '.repeat(lives)+'♡ '.repeat(3-lives);$('#hearts').setAttribute('aria-label',`${lives} de 3 vidas`);$('#score').textContent=`✦ ${score}`;$('#cue').textContent=l.type==='quiz'?`${step} / ${l.total} desafios · Pule os obstáculos`:l.type==='fly'?`${step} / ${l.total} letras · Segure para subir`:`${step} / 26 letras · Pule as pedras e caixas`}
function jump(){if(mode!=='run')return;held=true;if(levels[level].type==='fly')return;if(player.jumps<2){player.vy=-570*scale;player.jumps++;tone(true)}}
function pause(){if(mode!=='run')return;mode='pause';quiet();checkpoint();show(`<div class="eyebrow">UMA PAUSA NA AVENTURA</div><h2>Respire. O mundo espera.</h2><p>Seu progresso está guardado. Continue quando estiver pronto.</p><div class="modal-actions"><button class="primary" data-action="resume">Continuar ➜</button><button class="secondary" data-action="retry">Reiniciar fase</button></div><div class="modal-actions"><button class="secondary" data-action="home">Mapa dos mundos</button></div>`)}
function hurt(){if(invincible>0)return;mistakes++;combo=0;lives--;invincible=2.5;tone(false);burst(player.x,player.y-40*scale);if(lives<=0){mode='pause';quiet();checkpoint();show(`<div class="modal-symbol">↻</div><h2>Vamos tentar de novo?</h2><p>As descobertas que você fez continuam salvas. Você pode voltar ao mesmo ponto com três corações.</p><div class="modal-actions"><button class="secondary" data-action="home">Ver mapa</button><button class="primary" id="checkpoint">Tentar de novo ➜</button></div>`);$('#checkpoint').onclick=()=>start(level,true)}else{toast('Tudo bem! Vamos continuar.');hud()}}
function collect(o){step++;combo++;score+=50+(combo>=3?10:0);burst(o.x,o.y);tone();if(levels[level].type==='collect')speak(`${o.text} de ${words[step-1]}`);else speak(o.text);objects=objects.filter(a=>a!==o);checkpoint();if(step>=levels[level].total){finish();return}hud();spawnTime=1.1;}
function quizData(){if(level===1||level===3||level===4){let d=(level===1?initial:level===3?syllables:memory)[step];return{question:level===3?`Como começa ${d[0]}?`:`Qual é a primeira letra de ${d[0]}?`,answer:d[1],options:[d[1],...d[2]],hint:level===3?`${d[0]} começa com a sílaba ${d[1]}.`:`${d[0]} começa com a letra ${d[1]}.`}}if(level===5){let d=sentences[step];return{question:d[0],answer:d[1],options:[d[1],...d[2]],hint:d[0].replace('_____',d[1])}}let n=step+1;return{question:'Quantas estrelas você vê?',answer:String(n),options:[String(n),String(n===10?8:n+1),String(n===1?3:n-1)],hint:`São ${n} ${n===1?'estrela':'estrelas'}.`,count:n}}
function quiz(){mode='quiz';held=false;musicGame.volume=.07;let d=quizData(),options=d.options.slice();for(let i=options.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[options[i],options[j]]=[options[j],options[i]]}show(`<div class="eyebrow">PORTAL ${step+1} DE ${levels[level].total}</div><h2>${d.question}</h2>${d.count?`<div style="display:grid;grid-template-columns:repeat(5,1fr);gap:8px;color:#f1cc7d;font-size:33px;margin-top:20px" aria-label="Estrelas para contar">${Array.from({length:d.count},()=>'<span aria-hidden="true">★</span>').join('')}</div>`:'<p class="question-small">Escolha a resposta. Você pode tentar mais de uma vez.</p>'}<div class="answers">${options.map(v=>`<button class="answer" data-answer="${v}">${v}</button>`).join('')}</div><p id="answerFeedback" role="status" aria-live="polite"></p><div class="modal-actions"><button class="secondary" id="hearQuestion">◖)) Ouvir novamente</button><button class="secondary" data-action="home">Sair para o mapa</button></div>`);speak(d.question.replace('_____','espaço em branco'));$('#hearQuestion').onclick=()=>speak(d.question.replace('_____','espaço em branco'));body.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{if(b.dataset.answer===d.answer){b.classList.add('correct');body.querySelectorAll('[data-answer]').forEach(x=>x.disabled=true);$('#answerFeedback').textContent=d.hint;tone();speak(d.hint);step++;score+=100;combo++;checkpoint();pending=setTimeout(()=>{if(mode!=='quiz')return;close();musicGame.volume=.2;if(step>=levels[level].total)finish();else{mode='run';quizClock=0;spawnTime=1.4;objects=[];invincible=1;hud()}},1500)}else{mistakes++;combo=0;b.classList.add('wrong');b.disabled=true;$('#answerFeedback').textContent='Tente outra opção. Você consegue descobrir!';tone(false);checkpoint()}})}
function finish(){mode='result';quiet();objects=[];let stars=mistakes===0?3:mistakes<=3?2:1;save.best[level]=Math.max(save.best[level]||0,stars);if(!save.completed.includes(level))save.completed.push(level);save.resume=level<6?{level:level+1,step:0,score:0,mistakes:0}:null;persist();let all=save.completed.length===7;show(`<div class="eyebrow">${all?'JORNADA COMPLETA':'MUNDO CONCLUÍDO'}</div><h2>${all?'Um mundo de descobertas é seu!':levels[level].name+' conquistado!'}</h2><div class="stars" aria-label="${stars} de 3 estrelas">${'★'.repeat(stars)}${'☆'.repeat(3-stars)}</div><p>${all?'Isadora explorou os sete mundos. Você pode voltar ao mapa e brincar novamente em qualquer fase.':'Cada descoberta abre um novo caminho. Sua próxima aventura está esperando.'}</p><div class="stat-grid"><div><b>${score}</b>Pontos nesta fase</div><div><b>${step}</b>Descobertas</div><div><b>${save.completed.length}/7</b>Mundos concluídos</div></div><div class="modal-actions"><button class="secondary" data-action="home">Ver mapa</button><button class="primary" id="nextLevel">${level<6?'Próximo mundo ➜':'Jogar novamente ↻'}</button></div>`);$('#nextLevel').onclick=()=>intro(level<6?level+1:0,false);tone();if(all&&save.settings.effects)new Audio('assets/risada.mp3').play().catch(()=>{})}
function update(dt){if(mode!=='run')return;elapsed+=dt;time+=dt;const s=scale,conf=levels[level],speed=(save.settings.pace==='calm'?165:220)*s;distance+=speed*dt;invincible=Math.max(0,invincible-dt);if(conf.type==='fly'){player.vy+=(held?-700:430)*s*dt;player.vy=Math.max(-200*s,Math.min(180*s,player.vy));player.y+=player.vy*dt;let ceiling=Math.min(ground-30*s,220*s);player.y=Math.max(ceiling,Math.min(ground,player.y));if(player.y===ceiling||player.y===ground)player.vy=0}else{player.vy+=1450*s*dt;player.y+=player.vy*dt;if(player.y>=ground){player.y=ground;player.vy=0;player.jumps=0}}
spawnTime-=dt;quizClock+=dt;
if(conf.type==='quiz'){if(quizClock>7&&objects.length===0){quiz();return}if(spawnTime<=0&&quizClock<4.2){objects.push({kind:'hazard',x:W+65*s,w:48*s,h:40*s,variant:(level+step)%3});spawnTime=3.2}}
else if(spawnTime<=0&&!objects.some(o=>o.kind==='letter')){objects.push({kind:'letter',x:W+50*s,y:conf.type==='fly'?Math.max(160*s,ground-110*s-Math.sin(step*1.7)*50*s):ground-67*s,text:conf.type==='fly'?flight[step]:String.fromCharCode(65+step)});if(conf.type!=='fly'&&step>0&&step%2===1)objects.push({kind:'hazard',x:W+230*s,w:45*s,h:39*s,variant:step%3});spawnTime=3}
for(const o of [...objects]){o.x-=speed*dt;if(o.kind==='hazard'){if(Math.abs(o.x-player.x)<o.w*.43+17*s&&player.y>ground-o.h+10*s){hurt();o.x=-200;if(mode!=='run')break}}else{let dx=o.x-player.x,dy=o.y-(player.y-60*s);if(Math.abs(dx)<70*s&&Math.abs(dy)<115*s){collect(o);if(mode!=='run')break}else if(o.x<player.x-60*s){o.x=W+60*s;toast('A letra volta para você tentar de novo.')}}}objects=objects.filter(o=>o.x>-100*scale);for(let p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=220*dt;p.life-=dt*1.7}particles=particles.filter(p=>p.life>0);}
function settings(){show(`<div class="eyebrow">DO SEU JEITO</div><h2>Configurações</h2><label class="setting-row">Música <input id="musicSetting" type="checkbox" ${save.settings.music?'checked':''}></label><label class="setting-row">Narração em português <input id="voiceSetting" type="checkbox" ${save.settings.voice?'checked':''}></label><label class="setting-row">Efeitos sonoros <input id="effectsSetting" type="checkbox" ${save.settings.effects?'checked':''}></label><label class="setting-row">Partículas e movimento decorativo <input id="motionSetting" type="checkbox" ${save.settings.motion?'checked':''}></label><label class="setting-row">Velocidade <select id="paceSetting"><option value="calm">Tranquila</option><option value="adventure">Aventureira</option></select></label><p class="question-small">A voz usa os recursos disponíveis no navegador. Todos os objetivos também aparecem escritos.</p><div class="modal-actions"><button class="primary" id="saveSettings">Pronto</button></div>`);$('#paceSetting').value=save.settings.pace;$('#saveSettings').onclick=()=>{for(let k of ['music','voice','effects','motion'])save.settings[k]=$('#'+k+'Setting').checked;save.settings.pace=$('#paceSetting').value;persist();close();audio('menu');soundUI()}}
const story=[['Um presente do céu','Em Mirandiba, nasceu a pequena Isadora. Desde os primeiros dias, sua história foi cercada de carinho, cuidado e coragem.'],['Um lar em Recife','Quando a família viajou a Recife para a primeira cirurgia, encontrou apoio na Casa Sorrir: acolhimento, cuidado e amor. Ali, conheceu outras famílias e descobriu a força de caminhar junto.'],['Uma rede de cuidado','Com o apoio da Casa Sorrir, da família e da equipe médica, Isadora enfrentou uma etapa importante da sua história. Cada gesto de cuidado fez parte dessa caminhada.'],['O sorriso e as descobertas','A história da Isadora inspira esta aventura. Agora, cada letra, cada palavra e cada pequeno passo abre espaço para aprender e imaginar.']];
function book(){const p=story[bookPage];show(`<span class="story-progress">NOSSA HISTÓRIA · ${bookPage+1} / 4</span><canvas class="book-art" width="250" height="290"></canvas><h2>${p[0]}</h2><p>${p[1]}</p><div style="clear:both"></div><div class="modal-actions"><button class="secondary" id="bookPrev" ${bookPage===0?'disabled':''}>Anterior</button><button class="primary" id="bookNext">${bookPage===3?'Voltar ao início':'Próxima ➜'}</button></div>`);drawSprite(body.querySelector('canvas').getContext('2d'),125,285,265,bookPage%3);$('#bookPrev').onclick=()=>{bookPage--;book()};$('#bookNext').onclick=()=>{if(bookPage===3){close();bookPage=0}else{bookPage++;book()}}}
function soundUI(){document.querySelectorAll('[data-action="sound"]').forEach(b=>{b.textContent=save.settings.music?'♫':'♪';b.setAttribute('aria-pressed',String(save.settings.music));b.title=save.settings.music?'Desativar música':'Ativar música'})}
document.addEventListener('click',e=>{let b=e.target.closest('[data-action]');if(!b)return;switch(b.dataset.action){case'home':home();break;case'pause':pause();break;case'resume':close();mode='run';held=false;audio('game');break;case'retry':start(level);break;case'sound':save.settings.music=!save.settings.music;persist();audio(mode==='run'?'game':'menu');soundUI();break;case'settings':settings();break;case'book':bookPage=0;book();break;case'repeat':speak(objective());break;}});
$('#play').onclick=()=>intro(validResume()?save.resume.level:0,!!validResume());
$('#jump').addEventListener('pointerdown',e=>{e.preventDefault();$('#jump').setPointerCapture(e.pointerId);jump()});$('#jump').addEventListener('pointerup',()=>held=false);$('#jump').addEventListener('pointercancel',()=>held=false);$('#jump').addEventListener('lostpointercapture',()=>held=false);
canvas.addEventListener('pointerdown',e=>{if(mode==='run'){e.preventDefault();jump()}});addEventListener('pointerup',()=>held=false);addEventListener('keydown',e=>{if((e.code==='Space'||e.code==='ArrowUp')&&mode==='run'&&!modal.open){e.preventDefault();if(!e.repeat)jump()}else if((e.code==='Escape'||e.code==='KeyP')&&mode==='run'){e.preventDefault();pause()}else if(e.code==='KeyR'&&mode==='run')speak(objective())});addEventListener('keyup',e=>{if(e.code==='Space'||e.code==='ArrowUp')held=false});
modal.addEventListener('cancel',e=>{e.preventDefault();if(mode==='quiz')return;if(mode==='pause'){close();mode='run';audio('game')}else if(mode==='intro'||mode==='result')home();else close()});document.addEventListener('visibilitychange',()=>{if(document.hidden){if(mode==='run')pause();quiet();musicMenu.pause()}else if(mode==='home')audio('menu')});addEventListener('blur',()=>{held=false;if(mode==='run')pause()});
function tick(t){const dt=Math.min((t-last)/1000||0,.035);last=t;if(mode==='home'&&!reduced())time+=dt;update(dt);drawWorld();requestAnimationFrame(tick)}
Promise.all([art,sprite].map(img=>new Promise(resolve=>{if(img.complete)resolve();else{img.onload=resolve;img.onerror=resolve}}))).then(()=>{if(!sprite.naturalWidth){$('#loadText').textContent='Não foi possível carregar Isadora. Extraia a pasta completa e abra index.html novamente.';return}$('#loading').hidden=true;mode='home';$('#home').hidden=false;portrait();map();soundUI();requestAnimationFrame(tick)});
if('serviceWorker'in navigator&&/^https?:$/.test(location.protocol))navigator.serviceWorker.register('sw.js').catch(()=>{});
})();
